---
sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

stages:
  - check
  - analyze
  - test
  - release

jobs:
  include:
    - stage: check
      install:
      script:
        - make check
    - stage: analyze
      php: 7.1
      before_install:
        - sudo apt-get install -y dbview
      install:
        - phpenv config-rm xdebug.ini
        - composer install --prefer-dist
      script:
        - make PIndx.tsv
        - vendor/bin/phpunit
        - vendor/bin/php-cs-fixer --dry-run --stop-on-violation fix
        - composer validate
    - stage: release
      if: branch = master AND tag IS blank
      before_install: skip
      install: skip
      script:
        - . find-next-version 2>&1
        - git tag -a "$(. find-next-version)" -m "Automatic release"
      deploy:
        provider: script
        on:
          branch: master
          tags: true
        script: git push --tags

cache:
  directories:
    - $HOME/.composer
    - build/cache

addons:
  apt:
    update: true

install:
  - phpenv config-rm xdebug.ini || true
  - composer remove --no-update --dev friendsofphp/php-cs-fixer
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

