---
sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

stages:
  - check
  - analyze
  - test
  - deploy

jobs:
  include:
    - stage: check
      install:
      script:
        - make check
    - stage: analyze
      php: 7.1
      before_install:
        - sudo apt-get install -y dbview
      install:
        - phpenv config-rm xdebug.ini
        - composer install --prefer-dist
      script:
        - make PIndx.tsv
        - vendor/bin/phpunit
        - vendor/bin/php-cs-fixer --dry-run --stop-on-violation fix
        - composer validate

cache:
  directories:
    - $HOME/.composer
    - build/cache

addons:
  apt:
    update: true

install:
  - phpenv config-rm xdebug.ini || true
  - composer remove --no-update --dev friendsofphp/php-cs-fixer
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      condition: tag IS blank
    script:
      - git tag -a "$(. find-next-version)" -m "Automatic release"
      - git push --tags
