sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer
    - build/cache

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y dbview

install:
  - composer install --prefer-dist

script:
  - make PIndx.tsv
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer --dry-run --stop-on-violation fix
  - composer validate
